apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-scheduler
  template:
    metadata:
      labels:
        app: flight-scheduler
    spec:
      containers:
        - name: flight-scheduler
          image: sussap/flight-scheduler-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flight-scheduler
spec:
  type: NodePort
  selector:
    app: flight-scheduler
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002