name: Build and Push Flight Scheduler Service

on:
  workflow_dispatch:   # manual trigger
    inputs:
      tag:
        description: "Docker tag for the image"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build Docker image (explicitly use Dockerfile in docker/)
      - name: Build Docker image
        run: |
          docker build --no-cache -f docker/Dockerfile -t sussap/flight-scheduler-service:${{ github.event.inputs.tag }} .

      # Step 8: Push Docker image
      - name: Push Docker image
        run: |
          docker push sussap/flight-scheduler-service:${{ github.event.inputs.tag }}